### ISSUE TITLE
Broken calculator

### ISSUE THREAD

**Issue by ICS2663** [slowe/genderbias#3]
Hi there, just letting you know that the calculator is currently not working on Chrome and Safari. Neither is the Tom Forth version. FYI. I love this tool and would love it fixed. The examples work but not new copy.

**Comment by thomasforth** [comment]
Thanks for logging the issue. Unfortunately I cannot reproduce it. Chrome 84 64-bit on Windows 10.
![image](https://user-images.githubusercontent.com/606821/87616145-52265400-c70c-11ea-851d-06e28a421180.png)

**Comment by ICS2663** [comment]
Don’t you hate that?! I have Mac Retina 4K Intel Core i5 10.13.6 and Chrome Version 83.0.4103.116 (Official Build) (64-bit), but also couldn’t get it to work on Safari either. I’ve always been able to in the past though. Not sure what has changed.

Cheers,

Anne

[suits | Sneakers]<http://suitsandsneakers.global/>

Anne Miles

Managing Director

‘Pronouns: She/Her’

anne@suitsandsneakers.global<mailto:anne@suitsandsneakers.global>

M +61 411 102 401<tel:61411102401>

B 1300 804 372<tel:1300804372>

www.suitsandsneakers.global<http://suitsandsneakers.global/>




[National Finalist]


[Women in media Awards]


[200 | Businesses of Tomorrow 2018 Winner]


[Conscious Capitalism | Australia and New Zealand]

Suits&Sneakers acknowledges the traditional owners and custodians of the diverse lands we conduct our work.

**Comment by slowe** [comment]
@ICS2663 I've just tested it in Firefox 78 (Windows 10), Chrome 84 (Windows 10) and Safari (iOS 10.13) and it works in those. Nothing has changed with the code and it doesn't do anything clever that should cause security issues.

**Comment by ICS2663** [comment]
Not sure what to say with a dead end message. I’m not making it up…

It used to work and I sent a lot of people to it. Now it doesn’t work I won’t be able to.

Cheers,

Anne

[suits | Sneakers]<http://suitsandsneakers.global/>

Anne Miles

Managing Director

‘Pronouns: She/Her’

anne@suitsandsneakers.global<mailto:anne@suitsandsneakers.global>

M +61 411 102 401<tel:61411102401>

B 1300 804 372<tel:1300804372>

www.suitsandsneakers.global<http://suitsandsneakers.global/>




[National Finalist]


[Women in media Awards]


[200 | Businesses of Tomorrow 2018 Winner]


[Conscious Capitalism | Australia and New Zealand]

Suits&Sneakers acknowledges the traditional owners and custodians of the diverse lands we conduct our work.

**Comment by thomasforth** [comment]
For us, realistically, if we can't reproduce the problem (I've now tried all the browsers on five different computers and phones and it works fine), we can't fix it. My best guess (and still a low probability of it being right) is that the problem is with your computer or internet connection. Perhaps an anti-virus program, a security setting, a corporate security policy either on the computer or the network, a blocking decision by your ISP (I'm not current on Australian policies on web freedoms), or maybe even a virus/malware infection on your device.

We will keep our eyes open for any other reports and keep testing. Thanks again for your report and sorry we don't have a better resolution yet.

**Comment by slowe** [comment]
@ICS2663 Anne, is Javascript disabled in your browsers?
