### ISSUE TITLE
Some gender-neutral terms in my field

### ISSUE THREAD

**Issue by francoisluks** [slowe/genderbias#6]
I am new to this, so forgive me if this has been brought up before; either way, I would appreciate any help.
I have been using the Gender Bias calculator for a few years now, and I really like it - but: there are a few 'male' terms that, in my field, are not so much gender-related as they are academic career-related (see below). For example, someone who has many publications, grants and/or manuscripts is typically someone who is further along in their career, not more likely male. (I realize that there is a gender disparity at the top of academia, but if I praise someone for their publications or grants, it doesn't mean that they are male: case in point, the last 10 letters I wrote to support promotion of women surgeons all skewed heavily male. 

(If the algorithm skews male for a female candidate, is that seen as a compliment??)

Is there a way to alter the calculator for specific fields or study or profession?

Thanks

"experiment\\w*"
"scholarship"
"result\\w*"
"publication\\w*"
"publish\\w*"
"manuscript\\w*"
"project\\w*"
"grant"

**Comment by slowe** [comment]
@francoisluks The original research that this was based on makes the point that "letters for male applicants included more reference to 'his research,' 'his ability', or 'his career,' whereas letters for female applicants included more reference to 'her teaching,' or 'her training.'". I didn't come up with the word list. Changes to the word list (or additional, subject-specific, word lists) should come from proper research into the area. Just because we'd like various words to be neutral, unfortunately, doesn't make them that. This should be evidence-based as much as possible.

Yes, ideally none of these word would be used more for women or men. Then it wouldn't matter which you used. But, in a society which has long favoured men and disadvantaged women, using language that (unconsciously or not) furthers the existing biases is a problem. It isn't that "skew[ing] male for a female candidate" is a "compliment". It is about you, as someone writing a recommendation letter, being aware when your wording is disadvantaging women (and advantaging men).

Yes, you can fork this project and create your own personal word lists if you want. It is only a basic web page so doesn't require anything fancy to host it if you want your own.

**Comment by francoisluks** [comment]
Thanks for responding!
I cannot disagree with you, and I am certainly not suggesting that the
algorithm should be tweaked to better satisfy my needs, or heaven forbid,
my own biases. That said, context matters, and the letters that I write
vary from recommendations for trainees to support letters for peers.
Ultimately, you program makes me try to be a better letter writer, and its
transparency is helpful: it is easy enough to omit the trigger words that
are related to the person's career stage (research v. teaching, for
example) when running the letter through the program.

Again, I appreciate your taking the time to respond.

Francois Luks

**Comment by slowe** [comment]
I'm glad it is useful to you. Another person opened an issue to tell me it wasn't useful!

If you download a zip of the files you could make your own version specific for your field. Perhaps edit `https://github.com/slowe/genderbias/blob/main/dictionaries/medical.json` to create your own custom dictionary then make sure that dictionary JSON file is an <option> in `https://github.com/slowe/genderbias/blob/main/index.html`.
